// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hawsmswqnjlvboxfspll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhhd3Ntc3dxbmpsdmJveGZzcGxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMjQ2OTcsImV4cCI6MjA3MDkwMDY5N30.7GjpocwTZ0prOOM00htnMjrg1JQjNaSf6xPlolde6M0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});